version: "3.9"

services:
  web:
    restart: always
    build: ./auction-ui
    command: bash -c "yarn install &&
      yarn build &&
      yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ./auction-ui:/frontend
    networks:
      - db-net
    environment:
      - ENV=production
      - NEXT_PUBLIC_APP_API_SERVER_URL=https://qa.auctions.rigly.io

volumes:
  postgres_data:

networks:
  db-net:
    driver: bridge
