# Generated by Django 4.1.5 on 2023-02-19 09:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annoucement_message', models.CharField(blank=True, max_length=1500, null=True)),
                ('header_logo', models.FileField(blank=True, max_length=800, null=True, upload_to='images')),
            ],
            options={
                'verbose_name': 'Header Data',
                'verbose_name_plural': 'Header Data',
            },
        ),
        migrations.CreateModel(
            name='HomePageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('image_file', models.FileField(blank=True, null=True, upload_to='images')),
                ('mining_info_image_1', models.FileField(blank=True, max_length=800, null=True, upload_to='images')),
                ('mining_info_title_1', models.CharField(blank=True, max_length=500, null=True)),
                ('mining_info_description_1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('mining_info_url_1', models.CharField(blank=True, max_length=500, null=True)),
                ('mining_info_image_2', models.FileField(blank=True, max_length=800, null=True, upload_to='images')),
                ('mining_info_title_2', models.CharField(blank=True, max_length=500, null=True)),
                ('mining_info_description_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('mining_info_url_2', models.CharField(blank=True, max_length=500, null=True)),
                ('mining_info_image_3', models.FileField(blank=True, max_length=800, null=True, upload_to='images')),
                ('mining_info_title_3', models.CharField(blank=True, max_length=500, null=True)),
                ('mining_info_description_3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('mining_info_url_3', models.CharField(blank=True, max_length=500, null=True)),
                ('about_us_1_image', models.FileField(blank=True, max_length=800, null=True, upload_to='images')),
                ('about_us_1_title', models.CharField(blank=True, max_length=500, null=True)),
                ('about_us_1_sub_title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('about_us_1_url', models.CharField(blank=True, max_length=500, null=True)),
                ('about_us_2_image', models.FileField(blank=True, max_length=800, null=True, upload_to='images')),
                ('about_us_2_title', models.CharField(blank=True, max_length=500, null=True)),
                ('about_us_2_sub_title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('about_us_2_url', models.CharField(blank=True, max_length=500, null=True)),
                ('about_us_3_image', models.FileField(blank=True, max_length=800, null=True, upload_to='images')),
                ('about_us_3_title', models.CharField(blank=True, max_length=500, null=True)),
                ('about_us_3_sub_title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('about_us_3_url', models.CharField(blank=True, max_length=500, null=True)),
                ('show_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.collection')),
            ],
            options={
                'verbose_name': 'Home Page Data',
                'verbose_name_plural': 'Home Page Data',
            },
        ),
    ]
