# Generated by Django 4.1.5 on 2023-02-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagedata',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
