# Generated by Django 4.1.5 on 2023-02-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_homepagedata_image_file_homepagedata_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagedata',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
