# Generated by Django 4.1.5 on 2023-02-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_homepagedata_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagedata',
            name='image_url',
        ),
    ]
