# Generated by Django 4.1.5 on 2023-02-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_auctionlist_slug_auctionlist_slug_category'),
        ('api', '0004_remove_homepagedata_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagedata',
            name='show_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.collection'),
        ),
    ]
