# Generated by Django 4.1.5 on 2023-02-12 14:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_homepagedata_show_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annoucement_message', models.CharField(blank=True, max_length=1500, null=True)),
                ('header_logo', models.FileField(blank=True, max_length=800, null=True, upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='about_us_1_image',
            field=models.FileField(blank=True, max_length=800, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='about_us_1_sub_title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='about_us_1_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='about_us_1_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='about_us_2_image',
            field=models.FileField(blank=True, max_length=800, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='about_us_2_sub_title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='about_us_2_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='about_us_2_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='about_us_3_image',
            field=models.FileField(blank=True, max_length=800, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='about_us_3_sub_title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='about_us_3_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='about_us_3_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='mining_info_description_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='mining_info_description_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='mining_info_description_3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='mining_info_image_1',
            field=models.FileField(blank=True, max_length=800, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='mining_info_image_2',
            field=models.FileField(blank=True, max_length=800, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='mining_info_image_3',
            field=models.FileField(blank=True, max_length=800, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='mining_info_title_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='mining_info_title_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='mining_info_title_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='mining_info_url_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='mining_info_url_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='mining_info_url_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
