# Generated by Django 4.1.5 on 2023-02-19 09:25

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_1', models.FileField(blank=True, max_length=800, null=True, upload_to='auction_profile_images')),
                ('profile_image_2', models.FileField(blank=True, max_length=800, null=True, upload_to='auction_profile_images')),
                ('profile_image_3', models.FileField(blank=True, max_length=800, null=True, upload_to='auction_profile_images')),
                ('site_photo', models.FileField(blank=True, max_length=800, null=True, upload_to='auction_profile_images')),
                ('live_feed_image', models.FileField(blank=True, max_length=800, null=True, upload_to='auction_profile_images')),
                ('hash_price_image', models.FileField(blank=True, max_length=800, null=True, upload_to='auction_profile_images')),
                ('power_source', models.CharField(blank=True, max_length=204, null=True)),
                ('asic_model', models.CharField(blank=True, max_length=204, null=True)),
                ('terms_link', models.CharField(blank=True, max_length=1504, null=True)),
                ('hashrate', models.CharField(blank=True, max_length=104, null=True)),
                ('location', models.CharField(blank=True, max_length=104, null=True)),
                ('current_hash_price', models.CharField(blank=True, max_length=64, null=True)),
                ('days_of_mining', models.CharField(blank=True, max_length=104, null=True)),
                ('hours_per_day', models.CharField(blank=True, max_length=104, null=True)),
            ],
            options={
                'verbose_name': 'Auction Meta Data',
                'verbose_name_plural': 'Auctions Meta Data',
            },
        ),
        migrations.CreateModel(
            name='AuctionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Immediate delivery', max_length=100)),
                ('percentage', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('version', models.CharField(default='v1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionList',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.basemodel')),
                ('title', models.CharField(max_length=64)),
                ('sub_title', models.CharField(blank=True, max_length=504, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('starting_bid', models.IntegerField()),
                ('auction_start_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_expired', models.BooleanField(default=False)),
                ('proxy_increement', models.IntegerField(default=2)),
                ('is_auction_active', models.BooleanField(default=True)),
                ('auction_status', models.CharField(default='enabled', max_length=100)),
                ('slug_category', models.SlugField(blank=True, default='', editable=False, max_length=250, null=True)),
                ('payment_address', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_address_qr', models.FileField(blank=True, max_length=800, null=True, upload_to='payment_qr')),
                ('auction_meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionmetadata')),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
            },
            bases=('auctions.basemodel',),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.basemodel')),
                ('collection_name', models.CharField(max_length=640)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
            bases=('auctions.basemodel',),
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.basemodel')),
                ('code', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Coupons',
                'verbose_name_plural': 'Coupons',
            },
            bases=('auctions.basemodel',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.basemodel')),
                ('payment_status', models.CharField(max_length=100)),
                ('transaction_id', models.TextField()),
                ('extra_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
            bases=('auctions.basemodel',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_coupon_used', models.BooleanField(default=False)),
                ('profile_pik', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.coupons')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.payment')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProxyBids',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.basemodel')),
                ('maximum_amount', models.IntegerField(default=0)),
                ('history_values', models.TextField(default='')),
                ('auction_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proxy Bide',
                'verbose_name_plural': 'Proxy Bids',
            },
            bases=('auctions.basemodel',),
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.basemodel')),
                ('bid', models.IntegerField()),
                ('auction_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bide',
                'verbose_name_plural': 'Bids',
            },
            bases=('auctions.basemodel',),
        ),
        migrations.CreateModel(
            name='AuctionResult',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.basemodel')),
                ('position', models.IntegerField(default=0)),
                ('bid_price', models.IntegerField(default=0)),
                ('is_winner', models.BooleanField(default=0)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auction Result',
                'verbose_name_plural': 'Auction Results',
            },
            bases=('auctions.basemodel',),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.collection'),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
