# Generated by Django 4.1.5 on 2023-02-04 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.basemodel')),
                ('code', models.CharField(max_length=200)),
            ],
            bases=('auctions.basemodel',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.basemodel')),
                ('payment_status', models.CharField(max_length=100)),
                ('transaction_id', models.TextField()),
            ],
            bases=('auctions.basemodel',),
        ),
        migrations.AddField(
            model_name='user',
            name='is_coupon_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.coupons'),
        ),
        migrations.AddField(
            model_name='user',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.payment'),
        ),
    ]
