# Generated by Django 4.1.5 on 2023-02-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist_auction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bidding_name',
            field=models.CharField(default='Anonymous', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='mining_pool_stratum_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mining_pool_username',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='newsletter_subscribe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
