# Generated by Django 4.1.5 on 2023-02-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_coupons_payment_user_is_coupon_used_user_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.basemodel')),
                ('collection_name', models.CharField(max_length=640)),
            ],
            bases=('auctions.basemodel',),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.collection'),
        ),
    ]
