# Generated by Django 4.1.5 on 2023-02-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_collection_alter_auctionlist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
