# Generated by Django 4.1.5 on 2023-02-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_user_bidding_name_user_mining_pool_stratum_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, default='300926', max_length=100, null=True),
        ),
    ]
