# Generated by Django 4.1.5 on 2023-02-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_basemodel_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='image_url',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
