# Generated by Django 4.1.5 on 2023-02-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_user_refer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uploaded_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_profile_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, default='8F7051E175', max_length=100, null=True),
        ),
    ]
