# Generated by Django 4.1.5 on 2023-02-08 14:13

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auctionlist_image_url_auctionlist_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='expiry_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
