# Generated by Django 4.1.5 on 2023-02-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlist_expiry_at_alter_auctionlist_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='expiry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
