# Generated by Django 4.1.5 on 2023-02-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlist_expiry_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='expiry_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
