# Generated by Django 4.1.5 on 2023-02-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_user_refer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, default='B71366BAE5', max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='auctionlist',
            table='auction_list',
        ),
    ]
