# Generated by Django 4.1.5 on 2023-02-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_user_refer_code_alter_auctionlist_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, default='C008D2E30B', max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='auctionlist',
            table=None,
        ),
    ]
