# Generated by Django 4.1.5 on 2023-02-08 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlist_expiry_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='expiry_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
