# Generated by Django 4.1.5 on 2023-03-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_user_refer_code_alter_auctionlist_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, default='8F0BD46919', max_length=100, null=True),
        ),
    ]
