# Generated by Django 4.1.5 on 2023-03-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_user_refer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, default='0130EB6892', max_length=100, null=True),
        ),
    ]
