# Generated by Django 4.1.5 on 2023-03-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_user_refer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionresult',
            name='bid_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='proxybids',
            name='maximum_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, default='3F8605104B', max_length=100, null=True),
        ),
    ]
