# Generated by Django 4.1.5 on 2023-02-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlist_expiry_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='expiry_at',
        ),
    ]
