# Generated by Django 4.1.5 on 2023-03-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_auctionresult_bid_price_alter_bids_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, default='113A7BB333', max_length=100, null=True),
        ),
    ]
