# Generated by Django 4.1.5 on 2023-02-08 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_auctionlist_expiry_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='expiry_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
