# Generated by Django 4.1.5 on 2023-03-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_user_refer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pik',
            field=models.URLField(blank=True, default='https://auctions.rigly.io/media/auction_profile_images/profile_dummy.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, default='D4BCA46DEB', max_length=100, null=True),
        ),
    ]
