# Generated by Django 4.1.5 on 2023-02-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctionlist_expiry_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image_file',
            field=models.FileField(blank=True, max_length=800, null=True, upload_to='images'),
        ),
    ]
