# Generated by Django 4.1.5 on 2023-02-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auctionlist_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='slug',
            field=models.CharField(default='', max_length=640),
            preserve_default=False,
        ),
    ]
