# Generated by Django 4.1.5 on 2023-03-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_user_profile_pik_alter_user_refer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionPayment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.basemodel')),
                ('order_id', models.TextField()),
                ('payment_id', models.TextField()),
                ('price', models.BigIntegerField()),
                ('fee', models.BigIntegerField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('paid', 'Paid')], default='processing', max_length=10)),
            ],
            bases=('auctions.basemodel',),
        ),
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, default='EA5BFDEDAD', max_length=100, null=True),
        ),
    ]
