# Generated by Django 4.1.5 on 2023-03-03 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_user_profile_pik_alter_user_refer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.basemodel')),
                ('price', models.BigIntegerField()),
                ('fee', models.BigIntegerField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=7)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.auctionlist')),
            ],
            bases=('auctions.basemodel',),
        ),
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, default='CAE0DE6810', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.TextField(null=True)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('paid', 'Paid')], default='processing', max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.order')),
            ],
        ),
    ]
