# Generated by Django 4.1.5 on 2023-03-04 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_order_alter_user_refer_code_orderpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fee',
            new_name='auction_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='mining_deposit',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='original_amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='promo_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, default='AB2FB2F395', max_length=100, null=True),
        ),
    ]
