# Generated by Django 4.1.5 on 2023-03-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auctionpayment_alter_user_refer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, default='3DECB10FDD', max_length=100, null=True),
        ),
    ]
