# Generated by Django 4.1.5 on 2023-02-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auctionlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
