# Generated by Django 4.1.5 on 2023-02-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_auctionlist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='slug',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='slug_category',
            field=models.SlugField(blank=True, default='', editable=False, max_length=250, null=True),
        ),
    ]
