# Generated by Django 4.1.5 on 2023-02-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_auctionlist_slug_auctionlist_slug_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlist',
            old_name='image_file',
            new_name='hash_price_image',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='asic_model',
            field=models.CharField(blank=True, max_length=204, null=True),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='days_of_mining',
            field=models.CharField(blank=True, max_length=104, null=True),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='hashrate',
            field=models.CharField(blank=True, max_length=104, null=True),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='hours_per_day',
            field=models.CharField(blank=True, max_length=104, null=True),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='live_feed_image',
            field=models.FileField(blank=True, max_length=800, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='location',
            field=models.CharField(blank=True, max_length=104, null=True),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='power_source',
            field=models.CharField(blank=True, max_length=204, null=True),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='profile_image_1',
            field=models.FileField(blank=True, max_length=800, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='profile_image_2',
            field=models.FileField(blank=True, max_length=800, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='profile_image_3',
            field=models.FileField(blank=True, max_length=800, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='site_photo',
            field=models.FileField(blank=True, max_length=800, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='sub_title',
            field=models.CharField(blank=True, max_length=504, null=True),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='terms_link',
            field=models.CharField(blank=True, max_length=1504, null=True),
        ),
    ]
