# Generated by Django 4.1.5 on 2023-02-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_rename_image_file_auctionlist_hash_price_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='current_hash_price',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
