# Generated by Django 4.1.5 on 2023-02-10 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auctionlist_current_hash_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionResult',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.basemodel')),
                ('position', models.IntegerField(default=0)),
                ('bid_price', models.IntegerField(default=0)),
                ('is_winner', models.BooleanField(default=0)),
            ],
            bases=('auctions.basemodel',),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='auction_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Winner',
        ),
        migrations.AddField(
            model_name='auctionresult',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlist'),
        ),
        migrations.AddField(
            model_name='auctionresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
