# Generated by Django 4.1.5 on 2023-02-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auctionresult_auctionlist_auction_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='extra_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
