# Generated by Django 4.1.5 on 2023-02-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_payment_extra_info_alter_basemodel_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='auction_status',
            field=models.CharField(default='enabled', max_length=100),
        ),
    ]
