# Generated by Django 4.1.5 on 2023-02-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auctionlist_auction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pik',
            field=models.URLField(blank=True, null=True),
        ),
    ]
