name: Deploy PROD
on:
  push:
    branches: ["master"]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QA_HOST }}
          username: ${{ secrets.QA_USERNAME }}
          password: ${{ secrets.QA_PASSWORD }}
          port: ${{ secrets.QA_PORT }}
          script: |
            ./deploy_server.sh
